package com.cdc.fast.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-18T18:29:22.190+02:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://sei.ws.fast.cdc.com/", name = "DocumentService")
@XmlSeeAlso({ObjectFactory.class})
public interface DocumentService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.cdc.fast.ws.client.Download")
    @WebMethod
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.cdc.fast.ws.client.DownloadResponse")
    public com.cdc.fast.ws.client.DocumentContentVO download(
        @WebParam(name = "documentId", targetNamespace = "")
        java.lang.String documentId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "upload", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.cdc.fast.ws.client.Upload")
    @WebMethod
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.cdc.fast.ws.client.UploadResponse")
    public java.lang.String upload(
        @WebParam(name = "label", targetNamespace = "")
        java.lang.String label,
        @WebParam(name = "comment", targetNamespace = "")
        java.lang.String comment,
        @WebParam(name = "subscriberId", targetNamespace = "")
        java.lang.String subscriberId,
        @WebParam(name = "circuitId", targetNamespace = "")
        java.lang.String circuitId,
        @WebParam(name = "dataFile", targetNamespace = "")
        com.cdc.fast.ws.client.DataFile dataFile
    );
}
